title: krych14m's homepage
description: krych14m's homepage
baseurl: ""
url: "https://krych14m.github.io"

theme: minima

markdown: kramdown

plugins:
  - jekyll-sitemap

collections:
  pages:
    output: true
    permalink: /:name/
