title: krych14m's homepage
description: krych14m's homepage

theme: jekyll-theme-minimal

markdown: kramdown

plugins:
  - jekyll-sitemap

collections:
  pages:
    output: true
    permalink: /:name/
